version: 3.3 # CircleCI syntax version

orbs:
  heroku: circleci/heroku@0.0.10

jobs: # a collection of steps
  build: # runs that are not using Workflows must have a `build` job as the entry point
    docker:
      - image: circleci/node:14.16.0 # the first image is the primary container; this is where all `steps` will run
    steps: # a collection of executable commands
      - checkout # check out source code to working directory
      - restore_cache:
          name: Restore Dependency Cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: NPM Install
          command: npm install
      - save_cache:
          name: Save Dependency Cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: # run tests
          name: Run Tests and Coverage
          command: npm test
      - store_artifacts:
          path: coverage/lcov-report
          destination: coverage
workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build
          filters:
            branches:
              only: iteration2
